### ISSUE TITLE
Option for source attribute to be a class or Id

### ISSUE THREAD

**Issue by danmenza** [mhuggins/simple_form_autocomplete#4]
Trying to integrate Mapbox with simple_form. Mapbox uses an <input> id/class to autofill city + address fields. I was wondering if it's possible to have the source be an id or class instead of a list or URL

**Comment by mhuggins** [comment]
@danmenza I think you're looking for the [simple_form](https://github.com/heartcombo/simple_form) repo, but please correct me if I'm mistaken.
